name: Securigreffe Scraper

on:
  schedule:
    - cron: '0 */6 * * *'  # Exécution toutes les 6 heures
  workflow_dispatch:  # Permet l'exécution manuelle

jobs:
  scrape:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: |
        cd securigreffe
        npm install
        
    - name: Run scraper
      env:
        SECURIGREFFE_LOGIN: ${{ secrets.SECURIGREFFE_LOGIN }}
        SECURIGREFFE_PASSWORD: ${{ secrets.SECURIGREFFE_PASSWORD }}
      run: |
        cd securigreffe
        node login.js 