name: Scraper Securigreffe quotidien

on:
  schedule:
    - cron: '0 3 * * *' # Tous les jours à 3h du matin UTC
  workflow_dispatch:

jobs:
  run-scraper:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v3
      - name: Installation des dépendances
        run: npm install
        working-directory: securigreffe
      - name: Lancer le script de scraping
        run: node login.js
        working-directory: securigreffe
        env:
          LOGIN: ${{ secrets.SECURIGREFFE_LOGIN }}
          PASSWORD: ${{ secrets.SECURIGREFFE_PASSWORD }}
          WEBHOOK_URL_1: ${{ secrets.WEBHOOK_URL_1 }}
          WEBHOOK_URL_2: ${{ secrets.WEBHOOK_URL_2 }}
          SHEETS_GET_URL: ${{ secrets.SHEETS_GET_URL }} 