name: Scraper Securigreffe quotidien

on:
  schedule:
    - cron: '0 3 * * *' # Tous les jours à 3h du matin UTC
  workflow_dispatch:

jobs:
  run-scraper:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v3
      - name: Installation des dépendances
        run: npm install
        working-directory: .
      - name: Installer Chromium pour Puppeteer
        run: npx puppeteer browsers install chrome
      - name: Lancer le script de scraping
        run: node login.js
        working-directory: .
        env:
          SECURIGREFFE_LOGIN: ${{ secrets.SECURIGREFFE_LOGIN }}
          SECURIGREFFE_PASSWORD: ${{ secrets.SECURIGREFFE_PASSWORD }} 